version: '3'
services:
  server:
    build:
      context: ./backend/
    command: npm run dev
    volumes:
      - ./backend:/weatherapp_backend
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  client:
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend:/weatherapp_frontend
    depends_on:
      - server
    ports:
      - "8000:8000"
